version: "3.8"

services:
  # Контейнер для backend
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    environment:
      - DB_NAME=autoparts_shop
      - DB_USER=postgres
      - DB_PASSWORD=ps5694rus56
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app_network
    command: npm run dev

  # Контейнер для frontend
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend
    ports:
      - "3000:3004"
    networks:
      - app_network
    depends_on:
      - backend
    command: npm start

  # Контейнер для базы данных PostgreSQL
  db:
    image: postgres:17
    container_name: db
    environment:
      - POSTGRES_DB=autoparts_shop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ps5694rus56
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
